name: Windows Build Client

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'doc/**'
      - 'docker/**'
      - 'traces/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docker/**'
      - 'traces/**'
      - '.vscode/**'


jobs:
  proxspace:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    env:
      PATH: C:/ProxSpace/msys2/mingw64/bin;C:/ProxSpace/msys2/usr/local/bin;C:/ProxSpace/msys2/usr/bin;C:/ProxSpace/msys2/bin
      MSYSTEM: MINGW64
      PYTHONHOME: /mingw64

    steps:
      - name: ProxSpace download
        run: Invoke-WebRequest "https://github.com/Gator96100/ProxSpace/archive/master.zip" -outfile "C:\proxspace.zip" -Passthru

      - name: ProxSpace extract
        run: Expand-Archive -LiteralPath "C:\proxspace.zip" -DestinationPath "C:\"

      - name: ProxSpace delete zip
        run: Remove-Item "C:\proxspace.zip"

      - name: ProxSpace rename folder
        run: Get-ChildItem -Path "C:\ProxSpace-*" | Rename-Item -NewName (Split-Path C:\ProxSpace -Leaf)

      - name: ProxSpace version
        run: |
          $psversion = (Select-String -Pattern 'PSVERSION=' -SimpleMatch -Path "C:\ProxSpace\setup\09-proxspace_setup.post").Line.Split("""")[1]
          Write-Host "ProxSpace version: $psversion"

      - name: Checkout Proxmark3
        working-directory: C:\ProxSpace
        run: |
          mkdir ./pm3
          cd pm3
          git clone https://github.com/RfidResearchGroup/proxmark3.git

      - name: ProxSpace autobuild
        working-directory: C:\ProxSpace
        run: |
          ./autobuild.bat -c "exit"